/*
  Wizard Engine
  Copyright (C) 2023-2025 Zana Domán

  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/**
 * \file enumerations.hpp
 * \brief Enumerations.
 */

#ifndef WIZARD_ENGINE_UTILITIES_ENUMERATIONS_HPP
#define WIZARD_ENGINE_UTILITIES_ENUMERATIONS_HPP

#include <SDL3/SDL_log.h>
#include <SDL3/SDL_mouse.h>
#include <SDL3/SDL_scancode.h>
#include <SDL3/SDL_surface.h>
#include <SDL3_ttf/SDL_ttf.h>

#include <cstdint>

/**
 * \brief Utilities of Wizard Engine.
 */
namespace wizard_engine::utilities {
/**
 * \brief Flips.
 * \details Bitwise operations are supported.
 */
enum class flip : std::uint8_t {
  NONE = SDL_FLIP_NONE,
  HORIZONTAL = SDL_FLIP_HORIZONTAL,
  VERTICAL = SDL_FLIP_VERTICAL
};

/**
 * \brief Font alignments.
 * \details Bitwise operations are not supported.
 */
enum class font_alignment : std::uint8_t {
  LEFT = TTF_HORIZONTAL_ALIGN_LEFT,
  CENTER = TTF_HORIZONTAL_ALIGN_CENTER,
  RIGHT = TTF_HORIZONTAL_ALIGN_RIGHT,
  COUNT = 3
};

/**
 * \brief Font directions.
 * \details Bitwise operations are not supported.
 */
enum class font_direction : std::uint8_t {
  LEFT_TO_RIGHT = TTF_DIRECTION_LTR,
  RIGHT_TO_LEFT = TTF_DIRECTION_RTL,
  TOP_TO_BOTTOM = TTF_DIRECTION_TTB,
  BOTTOM_TO_TOP = TTF_DIRECTION_BTT,
  COUNT = 4
};

/**
 * \brief Font styles.
 * \details Bitwise operations are supported.
 */
enum class font_style : std::uint8_t {
  NORMAL = TTF_STYLE_NORMAL,
  BOLD = TTF_STYLE_BOLD,
  ITALIC = TTF_STYLE_ITALIC,
  UNDERLINE = TTF_STYLE_UNDERLINE,
  STRIKETHROUGH = TTF_STYLE_STRIKETHROUGH
};

/**
 * \brief Keys.
 * \details Bitwise operations are not supported.
 */
enum class key : std::uint16_t {
  UNKNOWN = SDL_SCANCODE_UNKNOWN,
  A = SDL_SCANCODE_A,
  B = SDL_SCANCODE_B,
  C = SDL_SCANCODE_C,
  D = SDL_SCANCODE_D,
  E = SDL_SCANCODE_E,
  F = SDL_SCANCODE_F,
  G = SDL_SCANCODE_G,
  H = SDL_SCANCODE_H,
  I = SDL_SCANCODE_I,
  J = SDL_SCANCODE_J,
  K = SDL_SCANCODE_K,
  L = SDL_SCANCODE_L,
  M = SDL_SCANCODE_M,
  N = SDL_SCANCODE_N,
  O = SDL_SCANCODE_O,
  P = SDL_SCANCODE_P,
  Q = SDL_SCANCODE_Q,
  R = SDL_SCANCODE_R,
  S = SDL_SCANCODE_S,
  T = SDL_SCANCODE_T,
  U = SDL_SCANCODE_U,
  V = SDL_SCANCODE_V,
  W = SDL_SCANCODE_W,
  X = SDL_SCANCODE_X,
  Y = SDL_SCANCODE_Y,
  Z = SDL_SCANCODE_Z,
  N1 = SDL_SCANCODE_1,
  N2 = SDL_SCANCODE_2,
  N3 = SDL_SCANCODE_3,
  N4 = SDL_SCANCODE_4,
  N5 = SDL_SCANCODE_5,
  N6 = SDL_SCANCODE_6,
  N7 = SDL_SCANCODE_7,
  N8 = SDL_SCANCODE_8,
  N9 = SDL_SCANCODE_9,
  N0 = SDL_SCANCODE_0,
  RETURN = SDL_SCANCODE_RETURN,
  ESCAPE = SDL_SCANCODE_ESCAPE,
  BACKSPACE = SDL_SCANCODE_BACKSPACE,
  TAB = SDL_SCANCODE_TAB,
  SPACE = SDL_SCANCODE_SPACE,
  MINUS = SDL_SCANCODE_MINUS,
  EQUALS = SDL_SCANCODE_EQUALS,
  LEFTBRACKET = SDL_SCANCODE_LEFTBRACKET,
  RIGHTBRACKET = SDL_SCANCODE_RIGHTBRACKET,
  BACKSLASH = SDL_SCANCODE_BACKSLASH,
  NONUSHASH = SDL_SCANCODE_NONUSHASH,
  SEMICOLON = SDL_SCANCODE_SEMICOLON,
  APOSTROPHE = SDL_SCANCODE_APOSTROPHE,
  GRAVE = SDL_SCANCODE_GRAVE,
  COMMA = SDL_SCANCODE_COMMA,
  PERIOD = SDL_SCANCODE_PERIOD,
  SLASH = SDL_SCANCODE_SLASH,
  CAPSLOCK = SDL_SCANCODE_CAPSLOCK,
  F1 = SDL_SCANCODE_F1,
  F2 = SDL_SCANCODE_F2,
  F3 = SDL_SCANCODE_F3,
  F4 = SDL_SCANCODE_F4,
  F5 = SDL_SCANCODE_F5,
  F6 = SDL_SCANCODE_F6,
  F7 = SDL_SCANCODE_F7,
  F8 = SDL_SCANCODE_F8,
  F9 = SDL_SCANCODE_F9,
  F10 = SDL_SCANCODE_F10,
  F11 = SDL_SCANCODE_F11,
  F12 = SDL_SCANCODE_F12,
  PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN,
  SCROLLLOCK = SDL_SCANCODE_SCROLLLOCK,
  PAUSE = SDL_SCANCODE_PAUSE,
  INSERT = SDL_SCANCODE_INSERT,
  HOME = SDL_SCANCODE_HOME,
  PAGEUP = SDL_SCANCODE_PAGEUP,
  DELETE = SDL_SCANCODE_DELETE,
  END = SDL_SCANCODE_END,
  PAGEDOWN = SDL_SCANCODE_PAGEDOWN,
  RIGHT = SDL_SCANCODE_RIGHT,
  LEFT = SDL_SCANCODE_LEFT,
  DOWN = SDL_SCANCODE_DOWN,
  UP = SDL_SCANCODE_UP,
  NUMLOCKCLEAR = SDL_SCANCODE_NUMLOCKCLEAR,
  KP_DIVIDE = SDL_SCANCODE_KP_DIVIDE,
  KP_MULTIPLY = SDL_SCANCODE_KP_MULTIPLY,
  KP_MINUS = SDL_SCANCODE_KP_MINUS,
  KP_PLUS = SDL_SCANCODE_KP_PLUS,
  KP_ENTER = SDL_SCANCODE_KP_ENTER,
  KP_1 = SDL_SCANCODE_KP_1,
  KP_2 = SDL_SCANCODE_KP_2,
  KP_3 = SDL_SCANCODE_KP_3,
  KP_4 = SDL_SCANCODE_KP_4,
  KP_5 = SDL_SCANCODE_KP_5,
  KP_6 = SDL_SCANCODE_KP_6,
  KP_7 = SDL_SCANCODE_KP_7,
  KP_8 = SDL_SCANCODE_KP_8,
  KP_9 = SDL_SCANCODE_KP_9,
  KP_0 = SDL_SCANCODE_KP_0,
  KP_PERIOD = SDL_SCANCODE_KP_PERIOD,
  NONUSBACKSLASH = SDL_SCANCODE_NONUSBACKSLASH,
  APPLICATION = SDL_SCANCODE_APPLICATION,
  POWER = SDL_SCANCODE_POWER,
  KP_EQUALS = SDL_SCANCODE_KP_EQUALS,
  F13 = SDL_SCANCODE_F13,
  F14 = SDL_SCANCODE_F14,
  F15 = SDL_SCANCODE_F15,
  F16 = SDL_SCANCODE_F16,
  F17 = SDL_SCANCODE_F17,
  F18 = SDL_SCANCODE_F18,
  F19 = SDL_SCANCODE_F19,
  F20 = SDL_SCANCODE_F20,
  F21 = SDL_SCANCODE_F21,
  F22 = SDL_SCANCODE_F22,
  F23 = SDL_SCANCODE_F23,
  F24 = SDL_SCANCODE_F24,
  EXECUTE = SDL_SCANCODE_EXECUTE,
  HELP = SDL_SCANCODE_HELP,
  MENU = SDL_SCANCODE_MENU,
  SELECT = SDL_SCANCODE_SELECT,
  STOP = SDL_SCANCODE_STOP,
  AGAIN = SDL_SCANCODE_AGAIN,
  UNDO = SDL_SCANCODE_UNDO,
  CUT = SDL_SCANCODE_CUT,
  COPY = SDL_SCANCODE_COPY,
  PASTE = SDL_SCANCODE_PASTE,
  FIND = SDL_SCANCODE_FIND,
  MUTE = SDL_SCANCODE_MUTE,
  VOLUMEUP = SDL_SCANCODE_VOLUMEUP,
  VOLUMEDOWN = SDL_SCANCODE_VOLUMEDOWN,
  KP_COMMA = SDL_SCANCODE_KP_COMMA,
  KP_EQUALSAS400 = SDL_SCANCODE_KP_EQUALSAS400,
  INTERNATIONAL1 = SDL_SCANCODE_INTERNATIONAL1,
  INTERNATIONAL2 = SDL_SCANCODE_INTERNATIONAL2,
  INTERNATIONAL3 = SDL_SCANCODE_INTERNATIONAL3,
  INTERNATIONAL4 = SDL_SCANCODE_INTERNATIONAL4,
  INTERNATIONAL5 = SDL_SCANCODE_INTERNATIONAL5,
  INTERNATIONAL6 = SDL_SCANCODE_INTERNATIONAL6,
  INTERNATIONAL7 = SDL_SCANCODE_INTERNATIONAL7,
  INTERNATIONAL8 = SDL_SCANCODE_INTERNATIONAL8,
  INTERNATIONAL9 = SDL_SCANCODE_INTERNATIONAL9,
  LANG1 = SDL_SCANCODE_LANG1,
  LANG2 = SDL_SCANCODE_LANG2,
  LANG3 = SDL_SCANCODE_LANG3,
  LANG4 = SDL_SCANCODE_LANG4,
  LANG5 = SDL_SCANCODE_LANG5,
  LANG6 = SDL_SCANCODE_LANG6,
  LANG7 = SDL_SCANCODE_LANG7,
  LANG8 = SDL_SCANCODE_LANG8,
  LANG9 = SDL_SCANCODE_LANG9,
  ALTERASE = SDL_SCANCODE_ALTERASE,
  SYSREQ = SDL_SCANCODE_SYSREQ,
  CANCEL = SDL_SCANCODE_CANCEL,
  CLEAR = SDL_SCANCODE_CLEAR,
  PRIOR = SDL_SCANCODE_PRIOR,
  RETURN2 = SDL_SCANCODE_RETURN2,
  SEPARATOR = SDL_SCANCODE_SEPARATOR,
  OUT = SDL_SCANCODE_OUT,
  OPER = SDL_SCANCODE_OPER,
  CLEARAGAIN = SDL_SCANCODE_CLEARAGAIN,
  CRSEL = SDL_SCANCODE_CRSEL,
  EXSEL = SDL_SCANCODE_EXSEL,
  KP_00 = SDL_SCANCODE_KP_00,
  KP_000 = SDL_SCANCODE_KP_000,
  THOUSANDSSEPARATOR = SDL_SCANCODE_THOUSANDSSEPARATOR,
  DECIMALSEPARATOR = SDL_SCANCODE_DECIMALSEPARATOR,
  CURRENCYUNIT = SDL_SCANCODE_CURRENCYUNIT,
  CURRENCYSUBUNIT = SDL_SCANCODE_CURRENCYSUBUNIT,
  KP_LEFTPAREN = SDL_SCANCODE_KP_LEFTPAREN,
  KP_RIGHTPAREN = SDL_SCANCODE_KP_RIGHTPAREN,
  KP_LEFTBRACE = SDL_SCANCODE_KP_LEFTBRACE,
  KP_RIGHTBRACE = SDL_SCANCODE_KP_RIGHTBRACE,
  KP_TAB = SDL_SCANCODE_KP_TAB,
  KP_BACKSPACE = SDL_SCANCODE_KP_BACKSPACE,
  KP_A = SDL_SCANCODE_KP_A,
  KP_B = SDL_SCANCODE_KP_B,
  KP_C = SDL_SCANCODE_KP_C,
  KP_D = SDL_SCANCODE_KP_D,
  KP_E = SDL_SCANCODE_KP_E,
  KP_F = SDL_SCANCODE_KP_F,
  KP_XOR = SDL_SCANCODE_KP_XOR,
  KP_POWER = SDL_SCANCODE_KP_POWER,
  KP_PERCENT = SDL_SCANCODE_KP_PERCENT,
  KP_LESS = SDL_SCANCODE_KP_LESS,
  KP_GREATER = SDL_SCANCODE_KP_GREATER,
  KP_AMPERSAND = SDL_SCANCODE_KP_AMPERSAND,
  KP_DBLAMPERSAND = SDL_SCANCODE_KP_DBLAMPERSAND,
  KP_VERTICALBAR = SDL_SCANCODE_KP_VERTICALBAR,
  KP_DBLVERTICALBAR = SDL_SCANCODE_KP_DBLVERTICALBAR,
  KP_COLON = SDL_SCANCODE_KP_COLON,
  KP_HASH = SDL_SCANCODE_KP_HASH,
  KP_SPACE = SDL_SCANCODE_KP_SPACE,
  KP_AT = SDL_SCANCODE_KP_AT,
  KP_EXCLAM = SDL_SCANCODE_KP_EXCLAM,
  KP_MEMSTORE = SDL_SCANCODE_KP_MEMSTORE,
  KP_MEMRECALL = SDL_SCANCODE_KP_MEMRECALL,
  KP_MEMCLEAR = SDL_SCANCODE_KP_MEMCLEAR,
  KP_MEMADD = SDL_SCANCODE_KP_MEMADD,
  KP_MEMSUBTRACT = SDL_SCANCODE_KP_MEMSUBTRACT,
  KP_MEMMULTIPLY = SDL_SCANCODE_KP_MEMMULTIPLY,
  KP_MEMDIVIDE = SDL_SCANCODE_KP_MEMDIVIDE,
  KP_PLUSMINUS = SDL_SCANCODE_KP_PLUSMINUS,
  KP_CLEAR = SDL_SCANCODE_KP_CLEAR,
  KP_CLEARENTRY = SDL_SCANCODE_KP_CLEARENTRY,
  KP_BINARY = SDL_SCANCODE_KP_BINARY,
  KP_OCTAL = SDL_SCANCODE_KP_OCTAL,
  KP_DECIMAL = SDL_SCANCODE_KP_DECIMAL,
  KP_HEXADECIMAL = SDL_SCANCODE_KP_HEXADECIMAL,
  LCTRL = SDL_SCANCODE_LCTRL,
  LSHIFT = SDL_SCANCODE_LSHIFT,
  LALT = SDL_SCANCODE_LALT,
  LGUI = SDL_SCANCODE_LGUI,
  RCTRL = SDL_SCANCODE_RCTRL,
  RSHIFT = SDL_SCANCODE_RSHIFT,
  RALT = SDL_SCANCODE_RALT,
  RGUI = SDL_SCANCODE_RGUI,
  MODE = SDL_SCANCODE_MODE,
  SLEEP = SDL_SCANCODE_SLEEP,
  WAKE = SDL_SCANCODE_WAKE,
  CHANNEL_INCREMENT = SDL_SCANCODE_CHANNEL_INCREMENT,
  CHANNEL_DECREMENT = SDL_SCANCODE_CHANNEL_DECREMENT,
  MEDIA_PLAY = SDL_SCANCODE_MEDIA_PLAY,
  MEDIA_PAUSE = SDL_SCANCODE_MEDIA_PAUSE,
  MEDIA_RECORD = SDL_SCANCODE_MEDIA_RECORD,
  MEDIA_FAST_FORWARD = SDL_SCANCODE_MEDIA_FAST_FORWARD,
  MEDIA_REWIND = SDL_SCANCODE_MEDIA_REWIND,
  MEDIA_NEXT_TRACK = SDL_SCANCODE_MEDIA_NEXT_TRACK,
  MEDIA_PREVIOUS_TRACK = SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,
  MEDIA_STOP = SDL_SCANCODE_MEDIA_STOP,
  MEDIA_EJECT = SDL_SCANCODE_MEDIA_EJECT,
  MEDIA_PLAY_PAUSE = SDL_SCANCODE_MEDIA_PLAY_PAUSE,
  MEDIA_SELECT = SDL_SCANCODE_MEDIA_SELECT,
  AC_NEW = SDL_SCANCODE_AC_NEW,
  AC_OPEN = SDL_SCANCODE_AC_OPEN,
  AC_CLOSE = SDL_SCANCODE_AC_CLOSE,
  AC_EXIT = SDL_SCANCODE_AC_EXIT,
  AC_SAVE = SDL_SCANCODE_AC_SAVE,
  AC_PRINT = SDL_SCANCODE_AC_PRINT,
  AC_PROPERTIES = SDL_SCANCODE_AC_PROPERTIES,
  AC_SEARCH = SDL_SCANCODE_AC_SEARCH,
  AC_HOME = SDL_SCANCODE_AC_HOME,
  AC_BACK = SDL_SCANCODE_AC_BACK,
  AC_FORWARD = SDL_SCANCODE_AC_FORWARD,
  AC_STOP = SDL_SCANCODE_AC_STOP,
  AC_REFRESH = SDL_SCANCODE_AC_REFRESH,
  AC_BOOKMARKS = SDL_SCANCODE_AC_BOOKMARKS,
  SOFTLEFT = SDL_SCANCODE_SOFTLEFT,
  SOFTRIGHT = SDL_SCANCODE_SOFTRIGHT,
  CALL = SDL_SCANCODE_CALL,
  ENDCALL = SDL_SCANCODE_ENDCALL,
  SCANCODE_RESERVED = SDL_SCANCODE_RESERVED,
  MOUSE_LEFT = 401,
  MOUSE_MIDDLE = 402,
  MOUSE_RIGHT = 403,
  MOUSE_X1 = 404,
  MOUSE_X2 = 405,
  MOUSE_WHEEL_UP = 406,
  MOUSE_WHEEL_DOWN = 407,
  SCANCODE_COUNT = 408
};

/**
 * \brief Log levels.
 * \details Bitwise operations are not supported.
 */
enum class log_level : std::uint8_t {
  INVALID = SDL_LOG_PRIORITY_INVALID,
  TRACE = SDL_LOG_PRIORITY_TRACE,
  VERBOSE = SDL_LOG_PRIORITY_VERBOSE,
  DEBUG = SDL_LOG_PRIORITY_DEBUG,
  INFO = SDL_LOG_PRIORITY_INFO,
  WARN = SDL_LOG_PRIORITY_WARN,
  ERROR = SDL_LOG_PRIORITY_ERROR,
  CRITICAL = SDL_LOG_PRIORITY_CRITICAL,
  COUNT = SDL_LOG_PRIORITY_COUNT
};

/**
 * \brief Cursor types.
 * \details Bitwise operations are not supported.
 */
enum class cursor_type : std::uint8_t {
  DEFAULT = SDL_SYSTEM_CURSOR_DEFAULT,
  TEXT = SDL_SYSTEM_CURSOR_TEXT,
  WAIT = SDL_SYSTEM_CURSOR_WAIT,
  CROSSHAIR = SDL_SYSTEM_CURSOR_CROSSHAIR,
  PROGRESS = SDL_SYSTEM_CURSOR_PROGRESS,
  NWSE_RESIZE = SDL_SYSTEM_CURSOR_NWSE_RESIZE,
  NESW_RESIZE = SDL_SYSTEM_CURSOR_NESW_RESIZE,
  EW_RESIZE = SDL_SYSTEM_CURSOR_EW_RESIZE,
  NS_RESIZE = SDL_SYSTEM_CURSOR_NS_RESIZE,
  MOVE = SDL_SYSTEM_CURSOR_MOVE,
  NOT_ALLOWED = SDL_SYSTEM_CURSOR_NOT_ALLOWED,
  POINTER = SDL_SYSTEM_CURSOR_POINTER,
  NW_RESIZE = SDL_SYSTEM_CURSOR_NW_RESIZE,
  N_RESIZE = SDL_SYSTEM_CURSOR_N_RESIZE,
  NE_RESIZE = SDL_SYSTEM_CURSOR_NE_RESIZE,
  E_RESIZE = SDL_SYSTEM_CURSOR_E_RESIZE,
  SE_RESIZE = SDL_SYSTEM_CURSOR_SE_RESIZE,
  S_RESIZE = SDL_SYSTEM_CURSOR_S_RESIZE,
  SW_RESIZE = SDL_SYSTEM_CURSOR_SW_RESIZE,
  W_RESIZE = SDL_SYSTEM_CURSOR_W_RESIZE,
  COUNT = SDL_SYSTEM_CURSOR_COUNT
};
}  // namespace wizard_engine::utilities

#endif  // WIZARD_ENGINE_UTILITIES_ENUMERATIONS_HPP
